version: '3.8'

services:
  frontend:
    build:
      context: ./web/usage-dashboard
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./web/usage-dashboard:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - CORS_ORIGINS=http://localhost:5173